[package]
name = "octobacilluscus"
version = "0.1.0"
edition = "2024"
authors = ["ekahPruthvi <ekahpdp@gmail.com>"]
description = "cynageOS lockscreen"
license = "GPL-3.0"

[dependencies]
gtk4 = "0.9.7"
gtk4-layer-shell = "0.5.0"
chrono = "0.4.41"

